name: build, api test, e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install  Angular CLI
        run: npm i -g @angular/cli

      - name: Install API dependencies
        working-directory: ./api
        run: dotnet restore

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm i && ng build

      - name: Build
        run: dotnet build
        working-directory: ./api

      - name: Start HTTP server
        working-directory: ./api
        run: dotnet run &
        env:
          pgconn: ${{secrets.PGCONN}}
      
      - name: Run setup for test
        run: cd TestProject1 && dotnet build && pwsh bin/Debug/net8.0/playwright.ps1 install
        
      - name: Run test
        working-directory: ./TestProject1
        run: dotnet test
